### ISSUE TITLE
Running MouseUnSnag at Windows startup, hidden in the background for a user

### ISSUE THREAD

**Issue by rudisills** [dale-roberts/MouseUnSnag#14]
It might be worth mentioning how to run this application hidden in the background at system startup. This is working for me.

1. Clone and build MouseUnSnag.exe

2. Create invisible.vbs (paste the following into invisible.vbs):
CreateObject("Wscript.Shell").Run """" & WScript.Arguments(0) & """", 0, False

3. Create MouseUnSnag.cmd (paste the following into MouseUnSnag.cmd, updating with your file locations):
C:/Windows/System32/wscript.exe "C:/Users/steve/bin/invisible.vbs" "C:/Users/steve/workspace/MouseUnSnag/MouseUnSnag.exe" //nologo

4. Move MouseUnSnag.cmd into the Windows Startup Folder:
C:\Users\steve\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

You can also navigate to the Windows Startup folder this way.
To access it, press Windows Key + R, type “shell:startup” into the Run dialog, and press Enter.

**Comment by patricknelson** [comment]
This is now possible in the latest release at the new project URL located at https://github.com/MouseUnSnag/MouseUnSnag.

The application starts as a system tray icon with the options exposed as checkboxes when right-clicked (or via `+[opt]` or `-[opt]` command line flags instead of `/opt` switches). Also: The retention of settings from the last startup is also already completed in our development version and may be available in the _**next**_ release (v2.2+ at the time of writing).

**EDIT:** Clarification: This is in reference to running in the background but not necessarily at startup. Running at startup is requested at https://github.com/MouseUnSnag/MouseUnSnag/issues/9 but can easily be accomplished via copying a shortcut to the app to your startup folder (e.g. you can get there via pressing <kbd>Win</kbd>+<kbd>r</kbd> and then `shell:startup` or by manually navigating to `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` with your username instead of `USERNAME`).

**Comment by dwolf42** [comment]
MouseUnSnag is mentioned in this video https://www.youtube.com/watch?v=twmnEx83Kqw which someone may find while searching for a solution for this mouse issue. If people then search for mouse unsnag via Google, they will find the original project site, https://github.com/dale-roberts/MouseUnSnag .
I was thinking about to not use it, since the description there says it won't run in background.

As I'm a curious person, I did have a little look around and found this issue here, in which I read about the new version. 
I think I might be a good idea to put some info in the read me of the old version about the new version :)

Cheers

**Comment by dale-roberts** [comment]
Great, glad you found the project! And thank you, yes, we were planning on putting a notice on this old project to direct people to the new one, once the new project had “settled”. It may be about that time now…

**Comment by patricknelson** [comment]
> And thank you, yes, we were planning on putting a notice on this old project to direct people to the new one, once the new project had “settled”. It may be about that time now…

Now that v2.2 is released (thanks to Grant) and this repo is now flagged as a fork, would now be a good time for that?

**Comment by dale-roberts** [comment]
Okay, done!
