### ISSUE TITLE
Disable personalized options when running since start up

### ISSUE THREAD

**Issue by xtreyreader** [dale-roberts/MouseUnSnag#15]
It would be useful to start up the program without having to disable "wrap around monitors" every time I start windows. Is there any way to do it already or can it be implemented? (assuming this project is not abandoned).

**Comment by patricknelson** [comment]
Nope @xtreyreader the project isn't abandoned! It just moved to https://github.com/MouseUnSnag/MouseUnSnag. I've discussed with @dale-roberts about the possibility of documenting this move to another project but I think we wanted to wait until maybe the next release before going fully public with that (see https://github.com/MouseUnSnag/MouseUnSnag/issues/2#issuecomment-997892433).

**Also:** The latest release presents a GUI (an icon in the system tray), however those options are not yet preserved in the current release (v2.1).  However, a _feature is already present_ in our current development branch but should be present in next upcoming release (2.2). I've already got an issue open at https://github.com/MouseUnSnag/MouseUnSnag/issues/11 to document this. However, until then, you can use my custom build at https://github.com/patricknelson/MouseUnSnag/releases which integrates all of my pull requests still pending at https://github.com/MouseUnSnag/MouseUnSnag/pulls/patricknelson which includes this ability to retain settings from the last startup.

cc @GrantMoyer, some motivation to merge those PR's and maybe move to releasing v2.2 so folks can make use of the latest work thus far (at least in an official release instead of my hack 😄).

**Comment by xtreyreader** [comment]
Oh thank you, adding -w to the startup shortcut is what I needed. Thank you for taking your time to do this, now it's a must.

**Comment by patricknelson** [comment]
I didn’t do it personally, I’m primarily a user with a tiny contribution here or there 😄 I’m thankful they added these options as well, though. This a super useful yet tiny app.

**Comment by patricknelson** [comment]
Hi @xtreyreader just FYI, the latest version v2.2 has been released which retains your personalized settings. https://github.com/MouseUnSnag/MouseUnSnag/releases
