### ISSUE TITLE
Command line argument to skip wraparound

### ISSUE THREAD

**Issue by gillius** [dale-roberts/MouseUnSnag#3]
Allow taking a command line parameter, such as /nowrap, which will skip the wrapping. The parameter can set a property on MouseUnSnag to make the call to WrapPoint optional.

As a workaround, it is possible to just delete these lines of code in MouseUnSnag.CheckJumpCursor

```cs
       else if (StuckDirection.X != 0)
        {
            NewCursor = WrapPoint (StuckDirection, cursor);
        }
```

BTW, thanks for the great instructions on compiling on Readme. I haven't done C# in about 16 years and I didn't realize how easy it was to compile (I don't have Visual Studio)! If I get time, when I get to my home machine where I can do a proper PR for this I will try to put it in. I had to compile it anyway because AV on my Chrome/Windows 10 blocks it as a virus, but I can see from the source it's clearly not malicious. This tool is great because I was constantly accidentally closing maximized windows on my left monitor since upgrading to Win 10!

**Comment by dale-roberts** [comment]
Thanks for the suggestion. Just a heads up, another Git user is in the process of making some contributions also. Unfortunately, since I’m a Git noob, I messed up his initial Pull Request, but hopefully we’ll get things straightened out shortly.

Yes, I agree the left/right mapping should be the first thing to optionally disable! Will do that…

dale

**Comment by gillius** [comment]
I saw that. I don't think the squash merge is really that big of a deal. The squash is nice because one feature is one commit that can be worked with easier. The preservation of history or not will be fought over until the end of time. Personally when I make a branch and commit a bunch of failed attempts and roll back a squash is nice to see the start-to-end result without the "dirty" parts along the way.

**Comment by dale-roberts** [comment]
Thanks, I’ll get used to this. I wanted to do this relatively small, fun little project to get used to how to work things on GitHub, and to hopefully learn from a few mistakes along the way. I realized after Drew’s comments that the Squash makes things harder if someone is in the middle of working on a particular branch, since the histories then diverge. Live and learn…

**Comment by patricknelson** [comment]
Thanks for the tip and the PR #4, @gillius! This overall solution was superior to mine ([win10-sticky-mouse](https://github.com/patricknelson/win10-sticky-mouse)), which was an AutoHotkey script, however I was about to decide to just not use it because of this weird quirk (since I'm typically on a dual monitor setup and this wrapping causes big issues when you're trying to scroll on the right side). Other folks may not realize that this is an option, so personally I think wrapping should be disabled by default. Either that, or at least document it **very** clearly.

Anyway @gillius, I've incorporated your revision along with some fixes to the PR (since the logic is backwards) and will be using this in conjunction with [RBTray](https://github.com/benbuck/rbtray/) to hide it away until my issue  #7 can be fixed (I'm a bit new to C# but I could maybe give it a shot later when I have more time and/or get sick of using RBTray 😂)

**Comment by patricknelson** [comment]
p.s. Also: Maybe this (along with issue #7) could be implemented as an INI config, so that settings are persisted across starts instead of via switches (and thus no CLI switches at all). That would make it easier to launch on startup as you see fit.

**Comment by GrantMoyer** [comment]
I started working on this before I realized someone else already was. Whoops. I've also made a PR that addresses the issue and adds options to disable the other features as well.

**Comment by patricknelson** [comment]
That PR is great; addresses more than just what's outlined here, which is fine. 

**My Q:**  @GrantMoyer  What is jump?  If that's what I think it is, that's awesome too since, while some may like it, I do not. I'm assuming this is the extra feature where it will "jump" the cursor back down if you're at a monitor edge where you have purposefully not aligned them (or if the resolutions/sizes differ), correct? i.e. Case 2 in the main `README.md` here (the diagonal dashed lines):

![68747470733a2f2f692e737461636b2e696d6775722e636f6d2f35526c6a692e706e67](https://user-images.githubusercontent.com/4269377/51511807-9f479500-1db7-11e9-86dd-85993d3020ae.png)

**Comment by GrantMoyer** [comment]
@patricknelson that is the jump feature my PR refers to. The wrap feature is feature 3 from the readme, and the unstick is feature number 1. All features can be controlled independently, and interact in what I think is the least surprising way.

**Comment by patricknelson** [comment]
a.k.a. https://en.wikipedia.org/wiki/Principle_of_least_astonishment

Thanks @GrantMoyer! 👍

**Comment by GrantMoyer** [comment]
I've Merged to open PR's on my fork, since there doesn't seem to be any activity here. and made a new PR with all the changes. I've also made a binary release with the changes on my fork.

**Comment by dale-roberts** [comment]
Grant, Thanks for charging ahead. Yes, sorry I’ve been a little lame with this project, but glad to see there is interest. Hopefully I’ll get back and eventually merge everything into the original project.

dale

**Comment by EddyStr** [comment]
I like the MouseUnSnag tool but without the warp around functionality. Currently I use the exe (1.0) which included wrap around, but could anyone please help me to get an .exe version without the wraparound function? Thanks :-)

**Comment by patricknelson** [comment]
@EddyStr it's a little tangled now, but... I remember issuing a PR for that exact capability (which is the version that I use daily now) on @gillius's fork of MouseUnSnag. See here: https://github.com/gillius/MouseUnSnag/pull/1 (based on his PR here https://github.com/dale-roberts/MouseUnSnag/pull/4)

It's pure code though. Thankfully the original author includes instructions on compiling this in the README: https://github.com/dale-roberts/MouseUnSnag#getting-started. Here are some instructions slapped together **(untested)** that _might_ work (I'm in a pinch on time):

```shell
# Get my nowrap version (wrapping disabled by default)
git clone git@github.com:patricknelson/MouseUnSnag.git
git checkout nowrap

# Compile code (install compiler, then compile)
nuget install Microsoft.Net.Compilers
Microsoft.Net.Compilers.2.6.1\tools\csc.exe MouseUnSnag.cs
```

**Comment by EddyStr** [comment]
@patricknelson thanks. I will try it out. Shall be hard for me as a real noob ;-)

**Comment by EddyStr** [comment]
@patricknelson thanks again and it was a struggle to get it all downloaded and compiled, but at the end I have the .bat file (MouseUnsnag-nowrap.bat) and your MouseUnSnag version (MouseUnSnag.exe). Now when I run the .bat file the program works perfectly, without the wrapping, but after some time it does not recognizes my mouse any more (or get stuck itself ;-)).  Do you have any idea?

**Comment by EddyStr** [comment]
@patricknelson <update> It happens with the original as well. Maybe it has something to do with my own system....

**Comment by patricknelson** [comment]
That used to happen to me as well. Not sure why it doesn't anymore, but what I usually did was just close and start it up again and then move it to another desktop and **_never minimize it_**. It's buggy I guess but at least it sorta gets the job done. Maybe someday when I have time, I can dust off some of my minimal C# experience and see what I can do to improve the app a little bit.

In the meantime... maybe it's motivation for you to dive into C#?! 😁

**Comment by GrantMoyer** [comment]
For posterity, I have a pre-built binary available in [my fork] with command line flags for wrap-around, jumping, and unsnagging. Each option is also controllable by right clicking the tray icon.

[my fork]: https://github.com/GrantMoyer/MouseUnSnag/releases

**Comment by patricknelson** [comment]
That's outstanding @GrantMoyer! Your version might now be my preferred one, thank you for sharing.

~~One minor issues (since I can't submit an issue on the fork itself, only PRs) is that the CLI usage help which should be output whenever an incorrect parameter is used isn't displayed at all (see below).~~ Moved to: https://github.com/MouseUnSnag/MouseUnSnag/issues/3. However, this is **far superior** to what I've been doing for the past few years so far. Essentially taking the command console and moving it over to another desktop on startup just to hide it. 😅

**Comment by patricknelson** [comment]
p.s. @GrantMoyer I might be interested in improving upon your fork since it seems like the best overall alternative to the original built by @dale-roberts. Could you enable Issues on your fork or are you no longer interested in maintaining it? Some examples are:

- Fix minor issue with switch/flag output (above)
- Ability to persist preferences after startup
- Unchecking "unstick from corners" doesn't actually allow sticking in the corners again (not that I'd ever want this, but it appears to not work)

No worries either way. I'm still thankful you took the time to improve upon it as it is! 😃

**Comment by GrantMoyer** [comment]
@patricknelson I've opened up Issues on my fork. I've merged together changes from all the existing up to date forks (really just @CSchwang's fork) in my merge_all branch, so if you want to work off my fork, you should work from there. In the near future, I'm going to move work to a MouseUnSnag organization (which will hopefully help create a de-facto standard version), and try to set up builds with GitHub actions.

**Comment by patricknelson** [comment]
Thanks @GrantMoyer! Link for the lazy: https://github.com/MouseUnSnag/MouseUnSnag

Submitting issues and PRs there now moving forward.

**Comment by EddyStr** [comment]
@GrantMoyer and @patricknelson thanks. It works perfectly :-)
